In [1]:
import tensorflow as tf

In [2]:
import keras
from keras.models import Sequential

In [3]:
#only model building part
model=Sequential()
model_part1=tf.keras.applications.ResNet50(
    include_top=False, #deletes the outer layer
    weights="imagenet",
    input_tensor=None,
    input_shape=(32,32,3), #according to X_train however check instructions on the page before use
    pooling='avg', #not required but preferred
    classes = 10 #according to yoour need
  
)
for layer in model_part1.layers:
    layer.trainable=False

In [4]:
from keras.layers import Flatten,Dense

In [5]:
model.add(model_part1)

In [6]:
model.add(Flatten())
model.add(Dense(512,activation='relu'))
model.add(Dense(10,activation='softmax'))

In [7]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 resnet50 (Functional)       (None, 2048)              23587712  
                                                                 
 flatten (Flatten)           (None, 2048)              0         
                                                                 
 dense (Dense)               (None, 512)               1049088   
                                                                 
 dense_1 (Dense)             (None, 10)                5130      
                                                                 
Total params: 24,641,930
Trainable params: 1,054,218
Non-trainable params: 23,587,712
_________________________________________________________________


In [8]:
fashion_mnist=keras.datasets.fashion_mnist

In [9]:
(X_train,Y_train),(X_test,Y_test)=fashion_mnist.load_data()

In [10]:
X_train.shape

(60000, 28, 28)

In [11]:



X_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [12]:
Y_train

array([9, 0, 0, ..., 3, 0, 5], dtype=uint8)

In [13]:
X_train[0].shape

(28, 28)

In [14]:
#it is grey scale
#it has fix size of 28,28

In [15]:
import cv2
import numpy as np
#X_train.setflags(write=1)

X_new = np.zeros((60000, 32, 32, 3), )

In [16]:

for i,fi in enumerate(X_train):
        img=cv2.resize(fi, (32,32), interpolation = cv2.INTER_AREA)
        img= cv2.cvtColor(img,cv2.COLOR_GRAY2RGB) #use loop for converting all image
       
        X_new[i] = img
           

In [17]:
model.compile(optimizer=keras.optimizers.Adam(learning_rate= 1e-3),
 loss= 'categorical_crossentropy',
 metrics=['accuracy'])

In [18]:
Y_train = tf.keras.utils.to_categorical(Y_train, 10)
Y_test = tf.keras.utils.to_categorical(Y_test, 10)

In [19]:
model.fit(X_new,Y_train)

1875/1875 [==============================] - 183s 97ms/step - loss: 0.5371 - accuracy: 0.8175


In [20]:
#import matplotlib.pyplot as plt



In [21]:
#plt.imshow(img)

In [22]:
#assignment 4
#deadline next friday
## use this code to build a ml model based on the given instructions
#convert all images to rgb
#use resnet50
X_test.shape

(10000, 28, 28)

In [23]:
Xp_new =  np.zeros((10000, 32, 32, 3), )

In [24]:
for i,fi in enumerate(X_test):
        img=cv2.resize(fi, (32,32), interpolation = cv2.INTER_AREA)
        img= cv2.cvtColor(img,cv2.COLOR_GRAY2RGB) #use loop for converting all image
       
        Xp_new[i] = img

In [25]:
Xp_new

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        ...,

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 

In [27]:
results = model.evaluate(Xp_new, Y_test)

313/313 [==============================] - 33s 99ms/step - loss: 0.4846 - accuracy: 0.8222


In [28]:
results

[0.484638512134552, 0.8222000002861023]